-- MySQL Script generated by MySQL Workbench
-- Sat Jun  8 03:03:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SCE_POSEC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SCE_POSEC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SCE_POSEC` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci ;
USE `SCE_POSEC` ;

-- -----------------------------------------------------
-- Table `SCE_POSEC`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`usuarios` (
  `usu_id` INT NOT NULL AUTO_INCREMENT,
  `usu_nombre` VARCHAR(64) NOT NULL,
  `usu_contrasena` VARCHAR(64) NOT NULL,
  `usu_rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`personal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`personal` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`personal` (
  `per_nombres` VARCHAR(45) NOT NULL,
  `per_apellidos` VARCHAR(45) NOT NULL,
  `per_fecha_nac` DATE NOT NULL,
  `per_num_personal` VARCHAR(20) NOT NULL,
  `per_num_telefono` VARCHAR(15) NOT NULL,
  `per_sexo` CHAR(1) NOT NULL,
  `pr_rfc` VARCHAR(13) NOT NULL,
  `per_turno` VARCHAR(15) NOT NULL,
  `usuarios_usu_id` INT NOT NULL,
  `per_estado` TINYINT NOT NULL,
  INDEX `fk_personal_usuarios1_idx` (`usuarios_usu_id` ASC),
  PRIMARY KEY (`pr_rfc`),
  CONSTRAINT `fk_personal_usuarios1`
    FOREIGN KEY (`usuarios_usu_id`)
    REFERENCES `SCE_POSEC`.`usuarios` (`usu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`recetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`recetas` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`recetas` (
  `rec_folio` INT NOT NULL AUTO_INCREMENT,
  `rec_fecha_vencimiento` DATE NOT NULL,
  `rec_fecha_creacion` DATE NOT NULL,
  `rec_instrucciones` TEXT NOT NULL,
  PRIMARY KEY (`rec_folio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`medicamento` (
  `med_codigo` INT NOT NULL AUTO_INCREMENT,
  `med_fecha_caducidad` DATE NOT NULL,
  `med_gramaje` FLOAT NOT NULL,
  `med_nombre` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`med_codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`recetas_medicamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`recetas_medicamentos` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`recetas_medicamentos` (
  `recmed_codigo` INT NOT NULL,
  `recmed_folio` INT NOT NULL,
  INDEX `fk_medicamento_has_recetas_recetas1_idx` (`recmed_folio` ASC),
  INDEX `fk_medicamento_has_recetas_medicamento_idx` (`recmed_codigo` ASC),
  CONSTRAINT `fk_medicamento_has_recetas_medicamento`
    FOREIGN KEY (`recmed_codigo`)
    REFERENCES `SCE_POSEC`.`medicamento` (`med_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicamento_has_recetas_recetas1`
    FOREIGN KEY (`recmed_folio`)
    REFERENCES `SCE_POSEC`.`recetas` (`rec_folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`pacientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`pacientes` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`pacientes` (
  `pac_num_seguro` INT NOT NULL,
  `pac_nombres` VARCHAR(100) NOT NULL,
  `pac_apellidos` VARCHAR(100) NOT NULL,
  `pac_fecha_nac` DATE NOT NULL,
  `pac_alergias` TEXT NOT NULL,
  `pac_sexo` CHAR(1) NOT NULL,
  `pac_num_telefono` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`pac_num_seguro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`consultas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`consultas` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`consultas` (
  `con_id` INT NOT NULL AUTO_INCREMENT,
  `con_diagnostico` TEXT NOT NULL,
  `con_estatura` FLOAT NOT NULL,
  `con_fecha` DATE NOT NULL,
  `con_hora_fin` TIME NOT NULL,
  `con_hora_inicio` TIME NOT NULL,
  `con_peso` FLOAT NOT NULL,
  `con_presion` VARCHAR(7) NOT NULL,
  `con_temperatura` FLOAT NOT NULL,
  `con_folio_receta` INT NOT NULL,
  `con_id_personal` INT NOT NULL,
  `con_seguro_paciente` INT NOT NULL,
  PRIMARY KEY (`con_id`),
  INDEX `fk_consultas_recetas1_idx` (`con_folio_receta` ASC),
  INDEX `fk_consultas_pacientes1_idx` (`con_seguro_paciente` ASC),
  CONSTRAINT `fk_consultas_recetas1`
    FOREIGN KEY (`con_folio_receta`)
    REFERENCES `SCE_POSEC`.`recetas` (`rec_folio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consultas_pacientes1`
    FOREIGN KEY (`con_seguro_paciente`)
    REFERENCES `SCE_POSEC`.`pacientes` (`pac_num_seguro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`citas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`citas` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`citas` (
  `cit_id` INT NOT NULL AUTO_INCREMENT,
  `cit_fecha_hora_reserva` TIMESTAMP NOT NULL,
  `cit_estado` INT NOT NULL DEFAULT 1,
  `cit_id_personal` INT NOT NULL,
  `cit_num_seguro_paciente` INT NOT NULL,
  PRIMARY KEY (`cit_id`),
  INDEX `fk_citas_pacientes1_idx` (`cit_num_seguro_paciente` ASC),
  CONSTRAINT `fk_citas_pacientes1`
    FOREIGN KEY (`cit_num_seguro_paciente`)
    REFERENCES `SCE_POSEC`.`pacientes` (`pac_num_seguro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SCE_POSEC`.`registros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SCE_POSEC`.`registros` ;

CREATE TABLE IF NOT EXISTS `SCE_POSEC`.`registros` (
  `reg_id` INT NOT NULL AUTO_INCREMENT,
  `reg_hora_entrada` TIME NOT NULL,
  `reg_hora_salida` TIME NULL,
  `reg_lugar_estadia` VARCHAR(100) NOT NULL,
  `personal_pr_rfc` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`reg_id`),
  INDEX `fk_registros_personal1_idx` (`personal_pr_rfc` ASC),
  CONSTRAINT `fk_registros_personal1`
    FOREIGN KEY (`personal_pr_rfc`)
    REFERENCES `SCE_POSEC`.`personal` (`pr_rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
