package Recursos;

/**
 *
 * @author Victor Javier
 */
public enum DatosPaciente {
    NOMBRE_VACIO,
    NOMBRE_LARGO,
    APELLIDO_VACIO,
    APELLIDO_LARGO,
    NUMERO_SEGURO_VACIO,
    NUMERO_TELEFONO_VACIO,
    NUMERO_TELEFONO_LARGO,
    NUMERO_TELEFONO_CORTO,
    FECHA_NACIMIENTO_VACIA,
    FECHA_NACIMIENTO_ACTUAL,
    SEXO_VACIO,
    ALERGIAS_VACIAS,
    ALERGIAS_LARGAS,
    VALIDO,
    EXITO,
    ERROR_ALMACENAMIENTO
}
